[package]
name = "pq_secure_file_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto = "0.17.0"
pqcrypto-ntru = "0.17.0"
ipfs-api-backend-hyper = "0.6.0"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
blake3 = "1.5.0"

